[workspace]
resolver = "2"
members = ["crates/*", "examples/*"]

[workspace.package]
edition = "2021"
authors = ["CrabNebula Ltd."]
license = "Apache-2.0 OR MIT"

[workspace.dependencies]
tauri = { version = "3.0.0-alpha.0", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2.0.20"
base64 = "0.23.1"
tao = "0.37.0"
winit = "0.30.13"
wry = "0.57.0"
dunce = "1.0.5"
tauri-build = "3.0.0-alpha.0"
tauri-runtime-wry = "3.0.0-alpha.0"
tauri-runtime-cef = "3.0.0-alpha.0"
tauri-plugin = { version = "3.0.0-alpha.0", features = ["build"] }
drag = { path = "./crates/drag", features = ["serde"] }
tauri-plugin-drag = { path = "./crates/tauri-plugin-drag" }
tauri-plugin-drag-as-window = { path = "./crates/tauri-plugin-drag-as-window" }
